image: maven:3.9.9-openjdk-17

pipelines:
  default:
    - step:
        name: "Run Selenium Tests"
        caches:
          - maven
        script:
          - mvn clean test
        artifacts:
          - target/surefire-reports/**